twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_name: 'Workoflow'
        supported_locales: '%app.supported_locales%'

when@test:
    twig:
        strict_variables: true