services:
  frankenphp:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    command: frankenphp run --config /etc/caddy/Caddyfile
    ports:
      - "3979:80"
      - "443:443"
    volumes:
      - ./var:/app/var
      - ./.env:/app/.env:ro
      - ./config/jwt:/app/config/jwt:ro
      - ./docker/frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - SERVER_NAME=:80
      - FRANKENPHP_CONFIG=worker ./public/index.php
      - APP_ENV=prod
      - APP_DEBUG=0
    depends_on:
      - mariadb
      - redis
    networks:
      - workoflow
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mariadb:
    image: mariadb:11.2
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - workoflow

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - workoflow

#  minio:
#    image: minio/minio:latest
#    restart: unless-stopped
#    environment:
#      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
#      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
#    volumes:
#      - minio_data:/data
#    command: server /data
#    ports:
#      - "9002:9000"
#      - "9003:9001"
#    networks:
#      - workoflow
#    healthcheck:
#      test: ["CMD", "mc", "ready", "local"]
#      interval: 30s
#      timeout: 20s
#      retries: 3

volumes:
  mariadb_data:
    external: true
  redis_data:
    external: true
  caddy_data:
    external: true
  caddy_config:
    external: true

networks:
  workoflow:
    driver: bridge
